<?php use Tecnodata\Lms\Core\Csrf; ?>
<div class="page-heading"><div><span class="eyebrow">REGRAS DO CURSO</span><h1><?=e($course['name'])?></h1><p>Configurações acadêmicas, conclusão, prazo, biometria e arquivos.</p></div><a class="btn btn-outline-secondary" href="/admin/courses/<?=$course['id']?>">Construtor</a></div>
<form method="post" action="/admin/courses/<?=$course['id']?>/settings">
<?=Csrf::field()?>
<div class="row g-3">
<div class="col-xl-6"><section class="panel h-100"><h2>Geral</h2><div class="row g-2"><div class="col-md-4"><label class="form-label">Código</label><input class="form-control" name="code" value="<?=e($course['code'])?>" required></div><div class="col-md-8"><label class="form-label">Nome</label><input class="form-control" name="name" value="<?=e($course['name'])?>" required></div><div class="col-md-6"><label class="form-label">Nome curto</label><input class="form-control" name="shortname" value="<?=e($course['shortname'])?>"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['draft'=>'Rascunho','published'=>'Publicado','hidden'=>'Oculto','archived'=>'Arquivado'] as $v=>$l):?><option value="<?=$v?>" <?=$course['status']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Navegação</label><select class="form-select" name="navigation_mode"><option value="linear" <?=$course['navigation_mode']==='linear'?'selected':''?>>Sequencial</option><option value="free" <?=$course['navigation_mode']==='free'?'selected':''?>>Livre</option></select></div><div class="col-12"><label class="form-label">Resumo</label><textarea class="form-control" rows="4" name="summary"><?=e($course['summary'])?></textarea></div></div></section></div>

<div class="col-xl-6"><section class="panel h-100"><h2>Conclusão e prazo</h2><div class="row g-2"><div class="col-md-4"><label class="form-label">Mínimo de dias</label><input class="form-control" type="number" min="0" name="min_days" value="<?=e($policy['min_days']??0)?>"></div><div class="col-md-4"><label class="form-label">Máximo de dias</label><input class="form-control" type="number" min="1" name="max_days" value="<?=e($policy['max_days']??'')?>"></div><div class="col-md-4"><label class="form-label">Conclusão mínima %</label><input class="form-control" type="number" min="0" max="100" step=".01" name="completion_percent" value="<?=e($policy['completion_percent']??100)?>"></div><div class="col-md-6"><label class="form-label">Nota final mínima</label><input class="form-control" type="number" step=".01" name="final_score_required" value="<?=e($policy['final_score_required']??'')?>"></div><div class="col-md-6"><label class="form-label">Perfil de validação</label><select class="form-select" name="biometric_profile_id"><?php foreach($bioProfiles as $p):?><option value="<?=$p['id']?>" <?=($bio['profile_id']??0)==$p['id']?'selected':''?>><?=e($p['name'])?></option><?php endforeach;?></select></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="require_sequential" id="seq" <?=!empty($policy['require_sequential'])?'checked':''?>><label class="form-check-label" for="seq">Exigir sequência das atividades</label></div><div class="form-check"><input class="form-check-input" type="checkbox" name="allow_retake" id="retake" <?=!isset($policy['allow_retake'])||$policy['allow_retake']?'checked':''?>><label class="form-check-label" for="retake">Permitir novas tentativas de avaliação</label></div></div></div></section></div>
</div>
<div class="mt-3"><button class="btn btn-brand">Salvar regras do curso</button></div>
</form>

<section class="panel mt-4"><div class="d-flex justify-content-between align-items-center"><div><h2>Arquivos do curso</h2><p class="text-secondary mb-0">PDFs, imagens e materiais ficam fora da pasta pública e exigem autenticação.</p></div></div>
<form method="post" enctype="multipart/form-data" action="/admin/courses/<?=$course['id']?>/files" class="row g-2 mt-2"><?=Csrf::field()?><div class="col-md-9"><input class="form-control" type="file" name="file" required></div><div class="col-md-3"><button class="btn btn-outline-secondary w-100">Enviar arquivo</button></div></form>
<div class="table-responsive mt-3"><table class="table align-middle"><thead><tr><th>Arquivo</th><th>Tipo</th><th>Tamanho</th><th>Data</th><th></th></tr></thead><tbody><?php foreach($files as $f):?><tr><td><a href="/files/<?=$f['id']?>" target="_blank"><?=e($f['original_name'])?></a></td><td><?=e($f['mime_type'])?></td><td><?=number_format($f['size_bytes']/1024/1024,2,',','.')?> MB</td><td><?=e($f['created_at'])?></td><td class="text-end"><form method="post" action="/admin/files/<?=$f['id']?>/delete"><?=Csrf::field()?><button class="btn btn-sm btn-outline-danger">Excluir</button></form></td></tr><?php endforeach;?></tbody></table></div>
</section>
