<?php use Tecnodata\Lms\Core\Csrf; ?>
<div class="page-heading"><div><span class="eyebrow">MATRÍCULA #<?=$enrollment['id']?></span><h1><?=e($enrollment['student'])?></h1><p><?=e($enrollment['course'])?> · <?=e($enrollment['course_code'])?></p></div><a class="btn btn-outline-secondary" href="/admin/enrollments">Voltar</a></div>
<div class="metric-grid"><div class="metric"><span>Status</span><strong style="font-size:22px"><?=e($enrollment['status'])?></strong></div><div class="metric"><span>Progresso</span><strong><?=e($enrollment['progress_percent'])?>%</strong></div><div class="metric"><span>Nota final</span><strong><?=e($enrollment['final_score']??'—')?></strong></div><div class="metric"><span>Tempo ativo</span><strong style="font-size:22px"><?=floor($study/3600)?>h <?=floor(($study%3600)/60)?>min</strong></div></div>
<div class="row g-3">
<div class="col-xl-4"><section class="panel h-100"><h2>Situação</h2><p><strong>CPF:</strong> <?=e($enrollment['cpf'])?></p><p><strong>E-mail:</strong> <?=e($enrollment['email']?:'—')?></p><p><strong>Início:</strong> <?=e($enrollment['started_at']?:'—')?></p><p><strong>Validade:</strong> <?=e($enrollment['expires_at']?:'—')?></p><p><strong>Conclusão:</strong> <?=e($enrollment['completed_at']?:'—')?></p><form method="post" action="/admin/enrollments/<?=$enrollment['id']?>/status"><?=Csrf::field()?><label class="form-label">Alterar status</label><select class="form-select mb-2" name="status"><?php foreach(['active'=>'Ativa','suspended'=>'Suspensa','cancelled'=>'Cancelada','completed'=>'Concluída','expired'=>'Expirada'] as $v=>$label):?><option value="<?=$v?>" <?=$enrollment['status']===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select><input class="form-control mb-2" name="reason" placeholder="Motivo / observação"><button class="btn btn-brand w-100">Salvar status</button></form></section></div>
<div class="col-xl-8"><section class="panel h-100"><h2>Progresso por atividade</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Atividade</th><th>Tipo</th><th>Progresso</th><th>Tempo</th><th>Conclusão</th></tr></thead><tbody><?php foreach($progress as $p):?><tr><td><?=e($p['title'])?></td><td><?=e($p['type'])?></td><td><?=e($p['progress_percent']??0)?>%</td><td><?=gmdate('H:i:s',(int)($p['seconds_spent']??0))?></td><td><?=e($p['completed_at']??'—')?></td></tr><?php endforeach;?></tbody></table></div></section></div>
</div>
<section class="panel mt-3"><h2>Tentativas de avaliação</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Prova</th><th>Tentativa</th><th>Nota</th><th>%</th><th>Resultado</th><th>Fim</th></tr></thead><tbody><?php foreach($attempts as $a):?><tr><td><?=e($a['quiz_title'])?></td><td><?=$a['attempt_no']?></td><td><?=e($a['score']??'—')?></td><td><?=e($a['percent']??'—')?></td><td><?=isset($a['passed'])?($a['passed']?'Aprovado':'Não aprovado'):'Em andamento'?></td><td><?=e($a['finished_at']??'—')?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel mt-3"><h2>Histórico de status</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Data</th><th>De</th><th>Para</th><th>Motivo</th><th>Alterado por</th></tr></thead><tbody><?php foreach($history as $h):?><tr><td><?=e($h['created_at'])?></td><td><?=e($h['old_status']??'—')?></td><td><?=e($h['new_status'])?></td><td><?=e($h['reason']??'')?></td><td><?=e($h['changed_by_name']?:'Sistema/API')?></td></tr><?php endforeach;?></tbody></table></div></section>
