<?php
require dirname(__DIR__).'/app/bootstrap.php';require APP_ROOT.'/app/Support/helpers.php';
use Tecnodata\CRM\Core\Auth;use Tecnodata\CRM\Core\DB;use Tecnodata\CRM\Services\GoalService;
Auth::requireLogin();if(!Auth::can('supervisor','admin')){http_response_code(403);exit;}
$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');
$sellers=DB::all("SELECT s.*,u.name user_name FROM sellers s LEFT JOIN users u ON u.seller_omie_code=s.omie_code AND u.active=1 WHERE s.active=1 ORDER BY s.name");
$modeLabels=['sales'=>'Somente vendas','collection'=>'Somente cobrança','sales_collection'=>'Vendas + cobrança'];include '_layout.php';?>
<div class="page-heading"><div><div class="eyebrow">GESTÃO • <?=date('m/Y',strtotime($month.'-01'))?></div><h1>Desempenho da equipe</h1><p>Indicadores exibidos conforme o perfil de cada vendedor.</p></div><input class="form-control month-control" type="month" value="<?=e($month)?>" onchange="location.href='?month='+this.value"></div>
<div class="panel-card"><div class="table-responsive data-table-wrap"><table class="table modern-table data-table mb-0" data-entity="vendedores" data-page-length="10"><thead><tr><th>Vendedor</th><th>Perfil</th><th>Vendas</th><th>Recuperado</th><th>Atendidos</th><th>Acordos</th><th>Devedores</th><th>Carteira devedora</th><th class="no-sort"></th></tr></thead><tbody>
<?php foreach($sellers as $seller):$goal=GoalService::sellerMonth((string)$seller['omie_code'],$month);$hasSales=$goal['has_sales'];$hasCollection=$goal['has_collection'];?>
<tr><td><div class="table-person"><span class="avatar avatar-sm"><?=e(mb_strtoupper(mb_substr($seller['name'],0,1)))?></span><div><strong><?=e($seller['name'])?></strong><small><?=e($seller['is_virtual']?'Operação virtual':($seller['user_name']??'Sem usuário vinculado'))?></small></div></div></td><td><span class="badge-soft"><?=e($modeLabels[$seller['goal_mode']]??'Perfil')?></span></td>
<td><?=$hasSales?money($goal['realized']).'<small class="table-sub">'.number_format($goal['percent'],1,',','.').'% da meta</small>':'<span class="text-secondary">Não se aplica</span>'?></td>
<td><?=$hasCollection?money($goal['collection_realized']).'<small class="table-sub">'.number_format($goal['collection_percent'],1,',','.').'% da meta</small>':'<span class="text-secondary">Não se aplica</span>'?></td>
<?php $usr=$seller['user_name']?DB::fetch("SELECT id FROM users WHERE seller_omie_code=? AND active=1 LIMIT 1",[$seller['omie_code']]):null;$start=$month.'-01';$next=date('Y-m-d',strtotime($start.' +1 month'));$st=$usr?DB::fetch("SELECT COUNT(DISTINCT client_id) worked,COUNT(DISTINCT CASE WHEN result='acordo' THEN client_id END) agreements FROM activities WHERE user_id=? AND deleted_at IS NULL AND created_at>=? AND created_at<?",[$usr['id'],$start,$next]):['worked'=>0,'agreements'=>0];?>
<td><?=(int)($st['worked']??0)?></td><td><?=(int)($st['agreements']??0)?></td><td><?=$hasCollection?$goal['debtors_worked'].'<small class="table-sub">meta '.$goal['contact_goal'].'</small>':'—'?></td><td><?=$hasCollection?money($goal['debtor_amount']).'<small class="table-sub">'.$goal['debtor_count'].' clientes</small>':'—'?></td><td><a class="icon-button" href="<?=APP_URL?>/vendedor.php?id=<?=$seller['id']?>&month=<?=e($month)?>"><i class="fa-solid fa-arrow-right"></i></a></td></tr>
<?php endforeach;?></tbody></table></div></div>
<?php include '_footer.php';?>
