<?php
require dirname(__DIR__).'/app/bootstrap.php';require APP_ROOT.'/app/Support/helpers.php';
use Tecnodata\CRM\Core\Auth;use Tecnodata\CRM\Core\DB;use Tecnodata\CRM\Core\Security;use Tecnodata\CRM\Services\GoalService;
Auth::requireLogin();if(!Auth::can('supervisor','admin')){http_response_code(403);exit;}$month=$_GET['month']??$_POST['month']??date('Y-m');
if($_SERVER['REQUEST_METHOD']==='POST'&&Security::verifyCsrf($_POST['_token']??null)){
 if(($_POST['goal_type']??'sales')==='collection'){foreach($_POST['collector']??[] as $uid=>$v){DB::exec("INSERT INTO collection_user_goals(user_id,month_ref,amount_goal,contact_goal,created_at,updated_at) VALUES(?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE amount_goal=VALUES(amount_goal),contact_goal=VALUES(contact_goal),updated_at=NOW()",[(int)$uid,$month,(float)($v['amount_goal']??0),(int)($v['contact_goal']??0)]);}}
 else DB::exec("INSERT INTO monthly_goals(month_ref,general_goal,created_at,updated_at) VALUES(?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE general_goal=VALUES(general_goal),updated_at=NOW()",[$month,(float)str_replace(',','.',$_POST['general_goal']??0)]);}
$collectors=DB::all("SELECT * FROM users WHERE role='collector' AND active=1 ORDER BY name");$sellers=DB::all("SELECT * FROM sellers WHERE active=1 ORDER BY goal_mode,name");$general=GoalService::generalMonth($month);$modeLabels=['sales'=>'Somente vendas','collection'=>'Somente cobrança','sales_collection'=>'Vendas + cobrança'];include '_layout.php';?>
<div class="page-heading"><div><div class="eyebrow">METAS • <?=date('m/Y',strtotime($month.'-01'))?></div><h1>Metas do mês</h1><p>Cada vendedor possui somente os indicadores correspondentes ao seu perfil.</p></div><input class="form-control month-control" type="month" value="<?=e($month)?>" onchange="location.href='?month='+this.value"></div>
<div class="panel-card mb-4"><div class="panel-header"><div><span>RESULTADO GERAL DE VENDAS</span><h2><?=money($general['realized'])?></h2></div><strong><?=number_format($general['percent'],1,',','.')?>%</strong></div><div class="panel-body"><form method="post" class="row g-3 align-items-end"><input type="hidden" name="_token" value="<?=Security::csrf()?>"><input type="hidden" name="month" value="<?=e($month)?>"><div class="col-md-5"><label class="form-label">Meta geral</label><input class="form-control" type="number" step="0.01" name="general_goal" value="<?=e((string)$general['goal'])?>"></div><div class="col-md-3"><button class="btn btn-primary w-100">Salvar meta</button></div><div class="col-md-4 text-md-end text-secondary">Produtos <?=money($general['product_realized'])?> • serviços <?=money($general['service_realized'])?></div></form></div></div>
<div class="seller-grid">
<?php foreach($sellers as $seller):$goal=GoalService::sellerMonth((string)$seller['omie_code'],$month);$hasSales=$goal['has_sales'];$hasCollection=$goal['has_collection'];$percent=$hasSales?$goal['percent']:$goal['collection_percent'];?>
<a class="seller-card" href="<?=APP_URL?>/vendedor.php?id=<?=$seller['id']?>&month=<?=e($month)?>"><div class="seller-card-top"><div class="avatar"><?=e(mb_strtoupper(mb_substr($seller['name'],0,1)))?></div><span class="badge-soft"><?=e($modeLabels[$seller['goal_mode']]??'Perfil')?></span></div><h2><?=e($seller['name'])?></h2><p><?=$hasSales?'Vendas: '.money($goal['realized']).' de '.money($goal['current']):'Recuperado: '.money($goal['collection_realized']).' de '.money($goal['collection_goal'])?></p><?php if($hasSales):?><small class="table-sub">Produtos <?=money($goal['product_realized'])?> • serviços <?=money($goal['service_realized'])?></small><?php endif;?><div class="mini-progress"><span style="width:<?=min(100,$percent)?>%"></span></div><div class="seller-meta"><?php if($hasCollection):?><span><i class="fa-solid fa-hand-holding-dollar"></i> <?=money($goal['collection_realized'])?> recuperados</span><span><?=$goal['debtors_worked']?> devedores</span><?php else:?><span><i class="fa-solid fa-chart-line"></i> 3 faixas de vendas</span><?php endif;?></div><div class="seller-card-footer"><strong><?=number_format($percent,1,',','.')?>%</strong><span>Ajustar metas <i class="fa-solid fa-arrow-right"></i></span></div></a>
<?php endforeach;?><?php if(!$sellers):?><div class="empty-state"><i class="fa-solid fa-bullseye"></i><h2>Nenhum vendedor ativo</h2></div><?php endif;?></div>

<div class="panel-card mt-4"><div class="panel-header"><div><span>COBRANÇA</span><h2>Metas da equipe de cobrança</h2></div><strong><?=count($collectors)?> usuários</strong></div><div class="panel-body"><form method="post"><input type="hidden" name="_token" value="<?=Security::csrf()?>"><input type="hidden" name="month" value="<?=e($month)?>"><input type="hidden" name="goal_type" value="collection"><div class="row g-3"><?php foreach($collectors as $collector):$cg=Tecnodata\CRM\Services\CollectionService::monthForUser((int)$collector['id'],$month);?><div class="col-xl-6"><div class="goal-editor"><div class="table-person mb-3"><span class="avatar"><?=e(mb_strtoupper(mb_substr($collector['name'],0,1)))?></span><div><strong><?=e($collector['name'])?></strong><small>Recuperado <?=money($cg['recovered'])?> • <?=$cg['worked']?> clientes</small></div></div><div class="row g-2"><div class="col-7"><label class="form-label">Meta de recuperação</label><input class="form-control" type="number" step="0.01" name="collector[<?=$collector['id']?>][amount_goal]" value="<?=$cg['amount_goal']?>"></div><div class="col-5"><label class="form-label">Clientes/mês</label><input class="form-control" type="number" min="0" name="collector[<?=$collector['id']?>][contact_goal]" value="<?=$cg['contact_goal']?>"></div></div></div></div><?php endforeach;?></div><?php if($collectors):?><button class="btn btn-dark mt-3"><i class="fa-solid fa-floppy-disk"></i>Salvar metas de cobrança</button><?php else:?><div class="empty-inline">Crie um usuário com perfil Cobrança para configurar metas.</div><?php endif;?></form></div></div>
<?php include '_footer.php';?>
