<?php
require dirname(__DIR__).'/app/bootstrap.php';require APP_ROOT.'/app/Support/helpers.php';
use Tecnodata\CRM\Core\Auth;use Tecnodata\CRM\Core\DB;use Tecnodata\CRM\Services\GoalService;
Auth::requireLogin();$user=Auth::user();$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');
$profile=$user['role']==='seller'&&!empty($user['seller_omie_code'])?DB::fetch('SELECT goal_mode FROM sellers WHERE omie_code=? AND active=1',[$user['seller_omie_code']]):null;if($user['role']==='seller'&&($profile['goal_mode']??'')==='collection'){http_response_code(403);exit('Este perfil possui somente cobrança.');}
$canManage=Auth::can('supervisor','admin');$sellers=$canManage?DB::all('SELECT omie_code,name FROM sellers WHERE active=1 ORDER BY name'):[];$sellerCode=$canManage?(string)($_GET['seller']??''):(string)($user['seller_omie_code']??'');
if($canManage&&$sellerCode!==''&&!array_filter($sellers,fn($seller)=>(string)$seller['omie_code']===$sellerCode))$sellerCode='';
$start=$month.'-01';$end=date('Y-m-t',strtotime($start));$params=[$start,$end];$where='so.inclusion_date BETWEEN ? AND ?';if(!$canManage&&$sellerCode==='')$where.=' AND 1=0';elseif($sellerCode!==''){$where.=' AND so.seller_omie_code=?';$params[]=$sellerCode;}
$services=DB::all("SELECT so.*,c.id client_id,c.name client_name,s.name seller_name FROM service_orders so LEFT JOIN clients c ON c.omie_code=so.client_omie_code LEFT JOIN sellers s ON s.omie_code=so.seller_omie_code WHERE {$where} ORDER BY so.inclusion_date DESC,so.id DESC",$params);
$valid=array_values(array_filter($services,fn($service)=>GoalService::isServiceOrderCounted($service)));$total=array_sum(array_map(fn($service)=>(float)$service['total'],$valid));$excluded=count($services)-count($valid);$average=count($valid)?$total/count($valid):0;$statuses=array_values(array_unique(array_column($services,'status')));sort($statuses);
include '_layout.php';?>
<div class="page-heading"><div><div class="eyebrow">SERVIÇOS • <?=date('m/Y',strtotime($start))?></div><h1>Ordens de Serviço</h1><p>Cursos e serviços ficam em uma base independente dos pedidos de produtos.</p></div><a class="btn btn-secondary" href="<?=APP_URL?>/sync.php"><i class="fa-solid fa-arrows-rotate"></i> Atualizar serviços</a></div>
<form class="toolbar-card orders-toolbar mb-4" method="get"><div><label class="form-label">Mês de inclusão</label><input class="form-control month-control" type="month" name="month" value="<?=e($month)?>"></div><?php if($canManage):?><div><label class="form-label">Vendedor</label><select class="form-select" name="seller"><option value="">Todos os vendedores</option><?php foreach($sellers as $seller):?><option value="<?=e($seller['omie_code'])?>" <?=$sellerCode===(string)$seller['omie_code']?'selected':''?>><?=e($seller['name'])?></option><?php endforeach;?></select></div><?php endif;?><button class="btn btn-primary"><i class="fa-solid fa-filter"></i> Aplicar período</button></form>
<div class="stat-grid stat-grid-4 mb-4"><div class="stat-card"><span>Valor válido para meta</span><strong><?=money($total)?></strong><small><?=count($valid)?> serviços considerados</small></div><div class="stat-card"><span>OS incluídas</span><strong><?=number_format(count($services),0,',','.')?></strong><small>no período selecionado</small></div><div class="stat-card"><span>Ticket médio</span><strong><?=money($average)?></strong><small>serviços considerados</small></div><div class="stat-card"><span>Fora da meta</span><strong><?=number_format($excluded,0,',','.')?></strong><small>orçamentos ou cancelamentos</small></div></div>
<div class="panel-card"><div class="panel-header orders-table-header"><div><span>DETALHAMENTO</span><h2>Lista de serviços</h2></div><div class="status-filter"><label for="serviceStatusFilter">Status</label><select class="form-select form-select-sm" id="serviceStatusFilter"><option value="">Todos</option><?php foreach($statuses as $status):?><option value="<?=e($status)?>"><?=e($status)?></option><?php endforeach;?></select></div></div>
<div class="table-responsive data-table-wrap"><table class="table modern-table data-table mb-0" data-entity="serviços" data-page-length="25" data-order-column="0" data-status-filter="#serviceStatusFilter" data-status-column="<?=$canManage?5:4?>"><thead><tr><th>Inclusão</th><th>OS</th><th>Cliente</th><th>Serviço / curso</th><?php if($canManage):?><th>Vendedor</th><?php endif;?><th>Status</th><th class="text-end">Valor</th><th class="no-sort"></th></tr></thead><tbody>
<?php foreach($services as $service):$isExcluded=!GoalService::isServiceOrderCounted($service);?>
<tr class="<?=$isExcluded?'order-ignored':''?>"><td data-order="<?=e($service['inclusion_date'])?>"><strong><?=brdate($service['inclusion_date'])?></strong></td><td><span class="order-number">#<?=e($service['display_number']?:$service['omie_service_order_code'])?></span><?php if($service['external_reference']):?><small class="table-sub"><?=e($service['external_reference'])?></small><?php endif;?></td><td><?=e($service['client_name']??'Cliente não localizado')?></td><td><?=e($service['service_description']?:'Serviço sem descrição')?></td><?php if($canManage):?><td><?=e($service['seller_name']??'Sem vendedor')?></td><?php endif;?><td><span class="badge-soft <?=$isExcluded?'badge-muted':($service['status']==='FATURADO'?'badge-success':'')?>"><?=e($service['stage_code']==='00'?'ORÇAMENTO':$service['status'])?></span><?php if($isExcluded):?><small class="table-sub">fora da meta</small><?php endif;?></td><td class="text-end" data-order="<?=(float)$service['total']?>"><strong class="order-value"><?=money($service['total'])?></strong></td><td><?php if($service['client_id']):?><a class="icon-button" href="<?=APP_URL?>/cliente.php?id=<?=$service['client_id']?>" title="Abrir cliente"><i class="fa-solid fa-arrow-up-right-from-square"></i></a><?php endif;?></td></tr><?php endforeach;?>
</tbody></table></div></div>
<?php include '_footer.php';?>
